#!/bin/sh
set -eu

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_dir="$(cd "$script_dir/.." && pwd)"
hooks_json="$repo_dir/config/hooks.json"
offsets_dir="$repo_dir/symbol-offsets"
out_header="$repo_dir/src/hook_config.h"

if [ ! -f "$hooks_json" ]; then
    echo "ERROR: hooks.json not found at $hooks_json" >&2
    exit 1
fi

echo "Generating hook_config.h..."
echo "  hooks.json : $hooks_json"
echo "  offsets dir: $offsets_dir"

# Generate C header
cat > "$out_header" <<'HEADER'
// Auto-generated by gen_hook_config.sh from config/hooks.json
// DO NOT EDIT MANUALLY
//
// 此文件包含：
//   1. struct hook_cfg     — 单个 hook 的配置（名称、库、偏移、retprobe）
//   2. hook_configs[]      — 所有 hook 的配置表（NUM_HOOKS 个）
//   3. struct module_meta  — 模块元信息（名称、前缀、ringbuf map 名）
//   4. modules[]           — 所有模块的元信息表（NUM_MODULES 个）
//   5. hook_name_tables[]  — 按 [module_id][hook_id] 查找 hook 名称

#pragma once

#include <stddef.h>
#include <stdbool.h>

// ── Hook 配置 ─────────────────────────────────────────────────────────

struct hook_cfg {
    const char *name;          // hook 名称，如 "rm_send_entry"
    const char *lib;           // 所属库文件名，如 "libvsomeip3.so.3.7.4"
    const char *target_path;   // 目标机器上的库路径，如 "/usr/lib/libvsomeip3.so.3"
    size_t     offset;         // 文件偏移量（用于 uprobe 挂载）
    bool       retprobe;       // true = uretprobe（返回探测）
};

// ── 模块元信息 ─────────────────────────────────────────────────────────

struct module_meta {
    const char *name;          // 模块名，如 "routing"
    const char *bpf_obj;       // BPF 对象文件名，如 "routing.bpf.o"
    const char *hook_prefix;   // hook 名前缀，如 "rm_"（用于筛选）
    const char *ringbuf_map;   // ringbuf map 名称，如 "routing_events"
    int         module_id;     // 模块 ID（对应 vsomeip_event.module_id）
    int         hook_count;    // 本模块的 hook 数量
};

HEADER

# Use python3 to parse JSON and generate all tables
python3 - "$hooks_json" "$offsets_dir" >> "$out_header" <<'PYTHON'
import json
import sys
import os

hooks_file = sys.argv[1]
offsets_dir = sys.argv[2]

with open(hooks_file) as f:
    config = json.load(f)

modules = config["modules"]
target_paths = config["target_paths"]
hooks = config["hooks"]

# ── 第一步：生成 hook_configs[] ───────────────────────────────────────
offset_cache = {}

def load_offsets(lib):
    if lib in offset_cache:
        return offset_cache[lib]
    offset_file = os.path.join(offsets_dir, f"{lib}.offsets.demangled.tsv")
    if not os.path.exists(offset_file):
        print(f"// ERROR: offset file not found: {offset_file}", file=sys.stderr)
        sys.exit(1)
    lookup = {}
    with open(offset_file) as f:
        f.readline()  # skip header
        for line in f:
            cols = line.rstrip('\n').split('\t')
            if len(cols) >= 7:
                lookup[cols[6]] = cols[0]
    offset_cache[lib] = lookup
    return lookup

print("")
print("static const struct hook_cfg hook_configs[] = {")

success = 0
failed = 0

# Build a map: hook_name -> hook info (for hook_name_tables later)
hook_info_map = {}

for hook in hooks:
    name = hook["name"]
    demangled = hook["demangled"]
    lib = hook["lib"]
    retprobe = 1 if hook.get("retprobe", False) else 0
    target_path = target_paths.get(lib, f"/usr/lib/{lib}")

    lookup = load_offsets(lib)
    offset = lookup.get(demangled)

    if offset is None:
        print(f'    // WARNING: symbol not found in {lib}: {name}')
        failed += 1
        continue

    print(f'    {{"{name}", "{lib}", "{target_path}", (size_t){offset}, {retprobe}}},')
    hook_info_map[name] = {"lib": lib, "offset": offset, "retprobe": retprobe}
    success += 1

print("};")
print(f"#define NUM_HOOKS {success}")
print("")

# ── 第二步：构建每个模块的 hook 列表（按 hook_id 顺序） ──────────────
# hook_id 是在 vsomeip_event.h 中定义的，从 0 开始连续编号。
# 我们按 hooks.json 中 hooks[] 的出现顺序来分配 hook_id，
# 因为 hooks.json 和 vsomeip_event.h 中声明的顺序是一致的。

# 先按模块收集 hook 名
module_hooks = {}  # module_name -> [hook_name, ...]
for mod in modules:
    module_hooks[mod["name"]] = []

for hook in hooks:
    name = hook["name"]
    if name not in hook_info_map:
        continue  # 符号查找失败的跳过
    # 找到这个 hook 属于哪个模块
    for mod in modules:
        if name.startswith(mod["hook_prefix"]):
            module_hooks[mod["name"]].append(name)
            break

# ── 第三步：生成 modules[] ────────────────────────────────────────────
print("static const struct module_meta modules[] = {")
for mod in modules:
    hcount = len(module_hooks[mod["name"]])
    print(f'    {{"{mod["name"]}", "{mod["bpf_obj"]}", "{mod["hook_prefix"]}", '
          f'"{mod["ringbuf_map"]}", {mod["module_id"]}, {hcount}}},')
print("};")
print(f"#define NUM_MODULES {len(modules)}")
print("")

# ── 第四步：生成 hook_name_tables ─────────────────────────────────────
# 格式：const char* hook_names_<module>[hook_count]
#       static const char** hook_name_tables[max_module_id+1]
#       索引 [module_id][hook_id] 即可查到名称

max_module_id = max(m["module_id"] for m in modules)

# 每个模块的 hook 名数组
for mod in modules:
    hnames = module_hooks[mod["name"]]
    mid = mod["module_id"]
    print(f"// {mod['name']} 模块的 hook 名（索引 = hook_id）")
    print(f"static const char* hook_names_{mod['name']}[] = {{")
    for h in hnames:
        print(f'    "{h}",')
    print("};")
    print("")

# 总表：按 module_id 索引
print("// 按 module_id 索引的总表（索引 0 为 NULL，模块 ID 从 1 开始）")
print(f"static const char** const hook_name_tables[{max_module_id + 1}] = {{")
print("    NULL,  // module_id = 0: 占位")
for mod in modules:
    mid = mod["module_id"]
    # 填充空位
    print(f"    hook_names_{mod['name']},  // module_id = {mid}: {mod['name']}")
print("};")
print("")

if failed > 0:
    print(f"// {failed} hooks FAILED to resolve (symbol not found in offset tables)")

print(f"// Generated: {success} hooks resolved, {len(modules)} modules, {failed} not found")

PYTHON

echo ""
echo "Generated: $out_header"
echo "Done."
