#!/bin/sh
set -eu

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_dir="$(cd "$script_dir/.." && pwd)"
hooks_json="$repo_dir/config/hooks.json"
offsets_dir="$repo_dir/symbol-offsets"
out_header="$repo_dir/src/hook_config.h"

if [ ! -f "$hooks_json" ]; then
    echo "ERROR: hooks.json not found at $hooks_json" >&2
    exit 1
fi

echo "Generating hook_config.h..."
echo "  hooks.json : $hooks_json"
echo "  offsets dir: $offsets_dir"

cat > "$out_header" <<'HEADER'
// Auto-generated by gen_hook_config.sh from config/hooks.json
// DO NOT EDIT MANUALLY
//
// 每个 file 条目 = 一个 Collector 实例 = 一个 .bpf.o + 一个 ringbuf map

#pragma once

#include <stddef.h>
#include <stdbool.h>

// ── Hook 运行时配置 ───────────────────────────────────────────────────

struct hook_cfg {
    const char *name;          // hook 名称，也是 SEC 程序名
    const char *target_path;   // 目标机器上的库路径
    size_t     offset;         // 文件偏移量（用于 uprobe 挂载）
    bool       retprobe;       // true = uretprobe
};

// ── 文件分组（一个分组 = 一个 Collector 实例）──────────────────────────

struct file_group {
    const char *bpf_obj;       // BPF 对象文件名，如 "routing.bpf.o"
    const char *ringbuf_map;   // ringbuf map 名称，如 "routing_events"
    int         module_id;     // 模块 ID（对应 vsomeip_event.module_id）
    int         hook_count;    // 本组的 hook 数量
    const struct hook_cfg *hooks;  // 指向本组的 hook 配置数组
    const char **hook_names;   // 指向本组的 hook 名数组（用于回调中查名称）
};

HEADER

python3 - "$hooks_json" "$offsets_dir" >> "$out_header" <<'PYTHON'
import json
import sys
import os

hooks_file = sys.argv[1]
offsets_dir = sys.argv[2]

with open(hooks_file) as f:
    config = json.load(f)

files = config["files"]

# ── 第一步：查偏移，生成每个 hook 的 hook_cfg 条目 ────────────────────
offset_cache = {}

def load_offsets(lib):
    if lib in offset_cache:
        return offset_cache[lib]
    offset_file = os.path.join(offsets_dir, f"{lib}.offsets.demangled.tsv")
    if not os.path.exists(offset_file):
        print(f"// ERROR: offset file not found: {offset_file}", file=sys.stderr)
        sys.exit(1)
    lookup = {}
    with open(offset_file) as f:
        f.readline()
        for line in f:
            cols = line.rstrip('\n').split('\t')
            if len(cols) >= 7:
                lookup[cols[6]] = cols[0]
    offset_cache[lib] = lookup
    return lookup

# 按文件分组生成 hook_cfg 数组和 hook 名数组
# 每个文件分组先输出其 hook_cfg 数组和 hook 名数组，
# 然后在 file_groups[] 中汇总

total_hooks = 0
file_group_names = []  # C 数组名列表

for fi, fg in enumerate(files):
    lib = fg["lib"]
    target_path = fg["target_path"]
    lookup = load_offsets(lib)

    # 生成本组的 hook_cfg 数组
    arr_name = f"hook_cfgs_{fg['bpf_obj'].replace('.','_')}"
    print(f"")
    print(f"// {fg['bpf_obj']} 的 hook 配置")
    print(f"static const struct hook_cfg {arr_name}[] = {{")
    for h in fg["hooks"]:
        offset = lookup.get(h["demangled"])
        if offset is None:
            print(f'    // WARNING: symbol not found: {h["name"]}', file=sys.stderr)
            continue
        rp = 1 if h.get("retprobe", False) else 0
        print(f'    {{"{h["name"]}", "{target_path}", (size_t){offset}, {rp}}},')
    print("};")

    # 生成本组的 hook 名数组（用于 ringbuf 回调中 hook_id → 名称）
    names_arr = f"hook_names_{fg['bpf_obj'].replace('.','_')}"
    print(f"static const char* {names_arr}[] = {{")
    for h in fg["hooks"]:
        print(f'    "{h["name"]}",')
    print("};")

    file_group_names.append((fg, arr_name, names_arr, len(fg["hooks"])))
    total_hooks += len(fg["hooks"])

# ── 第二步：生成 file_groups[] 汇总表 ─────────────────────────────────
print("")
print("// 文件分组表（一个分组 = 一个 Collector 实例）")
print("static const struct file_group file_groups[] = {")
for fg, arr_name, names_arr, hcount in file_group_names:
    print(f'    {{"{fg["bpf_obj"]}", "{fg["ringbuf_map"]}", '
          f'{fg["module_id"]}, {hcount}, {arr_name}, {names_arr}}},')
print("};")
print(f"#define NUM_FILE_GROUPS {len(files)}")
print(f"#define TOTAL_HOOKS {total_hooks}")

print(f"")
print(f"// Generated: {total_hooks} hooks, {len(files)} file groups")
PYTHON

echo ""
echo "Generated: $out_header"
echo "Done."
