#!/bin/sh
set -eu

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_dir="$(cd "$script_dir/.." && pwd)"
hooks_json="$repo_dir/config/hooks.json"
offsets_dir="$repo_dir/symbol-offsets"
out_header="$repo_dir/src/hook_config.h"

if [ ! -f "$hooks_json" ]; then
    echo "ERROR: hooks.json not found at $hooks_json" >&2
    exit 1
fi

echo "Generating hook_config.h..."
echo "  hooks.json : $hooks_json"
echo "  offsets dir: $offsets_dir"

# Generate C header
cat > "$out_header" <<'HEADER'
// Auto-generated by gen_hook_config.sh from config/hooks.json
// DO NOT EDIT MANUALLY

#pragma once

#include <stddef.h>
#include <stdbool.h>

/* Configuration for a single uprobe hook */
struct hook_cfg {
    const char *name;          /* human-readable hook name */
    const char *lib;           /* library key (for lookup) */
    const char *target_path;   /* path on target machine */
    size_t     offset;         /* file offset for uprobe */
    bool       retprobe;       /* true = uretprobe (return probe) */
};

HEADER

# Use python3 to parse JSON (more reliable than jq/shell parsing)
python3 - "$hooks_json" "$offsets_dir" >> "$out_header" <<'PYTHON'
import json
import sys
import os

hooks_file = sys.argv[1]
offsets_dir = sys.argv[2]

with open(hooks_file) as f:
    config = json.load(f)

target_paths = config["target_paths"]
hooks = config["hooks"]

# Build offset lookup: {lib: {demangled_name: offset_hex}}
offset_cache = {}

def load_offsets(lib):
    """Load demangled offsets for a given lib .so file."""
    if lib in offset_cache:
        return offset_cache[lib]

    offset_file = os.path.join(offsets_dir, f"{lib}.offsets.demangled.tsv")
    if not os.path.exists(offset_file):
        print(f"// ERROR: offset file not found: {offset_file}", file=sys.stderr)
        sys.exit(1)

    lookup = {}
    with open(offset_file) as f:
        header = f.readline()  # skip header
        for line in f:
            line = line.rstrip('\n')
            if not line:
                continue
            cols = line.split('\t')
            if len(cols) < 7:
                continue
            file_offset = cols[0]
            demangled = cols[6]
            lookup[demangled] = file_offset

    offset_cache[lib] = lookup
    return lookup

print("")
print("static const struct hook_cfg hook_configs[] = {")

success = 0
failed = 0

for hook in hooks:
    name = hook["name"]
    demangled = hook["demangled"]
    lib = hook["lib"]
    retprobe = 1 if hook.get("retprobe", False) else 0

    target_path = target_paths.get(lib, f"/usr/lib/{lib}")

    lookup = load_offsets(lib)
    offset = lookup.get(demangled)

    if offset is None:
        print(f'    // NOT FOUND: {name} -> "{demangled[:80]}..."', file=sys.stderr)
        print(f'    // WARNING: symbol not found in {lib}: {name}')
        failed += 1
        continue

    print(f'    {{"{name}", "{lib}", "{target_path}", (size_t){offset}, {retprobe}}},')
    success += 1

print("};")
print(f"#define NUM_HOOKS {success}")
print("")

if failed > 0:
    print(f"// {failed} hooks FAILED to resolve (symbol not found in offset tables)")

print(f"// Generated: {success} hooks resolved, {failed} not found")

PYTHON

echo ""
echo "Generated: $out_header"
grep -c "}," "$out_header" | xargs echo "  hooks:"
echo "Done."
