// Auto-generated by gen_hook_config.sh from config/hooks.json
// DO NOT EDIT MANUALLY
//
// 每个 file 条目 = 一个 Collector 实例 = 一组嵌入的 BPF 字节码 + 一个 ringbuf map

#pragma once

#include <stddef.h>
#include <stdbool.h>

// ── Hook 运行时配置 ───────────────────────────────────────────────────

struct hook_cfg {
    const char *name;          // hook 名称，也是 SEC 程序名
    const char *target_path;   // 目标机器上的库路径
    size_t     offset;         // 文件偏移量（用于 uprobe 挂载）
    bool       retprobe;       // true = uretprobe
};

// ── 文件分组（一个分组 = 一个 Collector 实例）──────────────────────────

struct file_group {
    const char *name;          // 逻辑标识，如 "routing"
    const void *embed_data;    // 指向嵌入的 BPF 字节码数组
    unsigned int embed_size;   // 字节码数组长度（和 xxd -i 生成的 _len 类型一致）
    const char *ringbuf_map;   // ringbuf map 名称
    int         module_id;     // 模块 ID（对应 vsomeip_event.module_id）
    int         hook_count;    // 本组的 hook 数量
    const struct hook_cfg *hooks;   // 指向本组的 hook 配置数组
    const char **hook_names;        // 指向本组的 hook 名数组
};


// ── 嵌入的 BPF 字节码（extern，实际定义在 bpf/embed_data.cpp）─────
extern unsigned char routing_bpf_o[];
extern unsigned int  routing_bpf_o_len;
extern unsigned char app_bpf_o[];
extern unsigned int  app_bpf_o_len;
extern unsigned char sd_bpf_o[];
extern unsigned int  sd_bpf_o_len;

// routing.bpf.o 的 hook 配置（5 个）
static const struct hook_cfg hook_cfgs_routing[] = {
    {"rm_send_entry", "/usr/lib/libvsomeip3.so.3", (size_t)0x0000000000169340, 0},
    {"rm_send_ret", "/usr/lib/libvsomeip3.so.3", (size_t)0x0000000000169340, 1},
    {"rm_send_to_entry", "/usr/lib/libvsomeip3.so.3", (size_t)0x000000000016a720, 0},
    {"rm_send_to_ret", "/usr/lib/libvsomeip3.so.3", (size_t)0x000000000016a720, 1},
    {"rm_on_message", "/usr/lib/libvsomeip3.so.3", (size_t)0x0000000000172630, 0},
};
static const char* hook_names_routing[] = {
    "rm_send_entry",
    "rm_send_ret",
    "rm_send_to_entry",
    "rm_send_to_ret",
    "rm_on_message",
};

// app.bpf.o 的 hook 配置（3 个）
static const struct hook_cfg hook_cfgs_app[] = {
    {"app_send_entry", "/usr/lib/libvsomeip3.so.3", (size_t)0x00000000001bb340, 0},
    {"app_send_ret", "/usr/lib/libvsomeip3.so.3", (size_t)0x00000000001bb340, 1},
    {"app_on_message", "/usr/lib/libvsomeip3.so.3", (size_t)0x00000000001bc670, 0},
};
static const char* hook_names_app[] = {
    "app_send_entry",
    "app_send_ret",
    "app_on_message",
};

// sd.bpf.o 的 hook 配置（4 个）
static const struct hook_cfg hook_cfgs_sd[] = {
    {"sd_send", "/usr/lib/libvsomeip3-sd.so.3", (size_t)0x000000000002c7e0, 0},
    {"sd_process_offer", "/usr/lib/libvsomeip3-sd.so.3", (size_t)0x0000000000038a30, 0},
    {"sd_send_subscription", "/usr/lib/libvsomeip3-sd.so.3", (size_t)0x0000000000035e80, 0},
    {"sd_handle_subscription", "/usr/lib/libvsomeip3-sd.so.3", (size_t)0x000000000002ea30, 0},
};
static const char* hook_names_sd[] = {
    "sd_send",
    "sd_process_offer",
    "sd_send_subscription",
    "sd_handle_subscription",
};

// 文件分组表（一个分组 = 一个 Collector 实例）
static const struct file_group file_groups[] = {
    {"routing", routing_bpf_o, routing_bpf_o_len, "routing_events", 1, 5, hook_cfgs_routing, hook_names_routing},
    {"app", app_bpf_o, app_bpf_o_len, "app_events", 2, 3, hook_cfgs_app, hook_names_app},
    {"sd", sd_bpf_o, sd_bpf_o_len, "sd_events", 3, 4, hook_cfgs_sd, hook_names_sd},
};
#define NUM_FILE_GROUPS 3
#define TOTAL_HOOKS 12

// Generated: 12 hooks, 3 file groups
