// Auto-generated by gen_hook_config.sh from config/hooks.json
// DO NOT EDIT MANUALLY

#pragma once

#include <stddef.h>
#include <stdbool.h>

/* Configuration for a single uprobe hook */
struct hook_cfg {
    const char *name;          /* human-readable hook name */
    const char *lib;           /* library key (for lookup) */
    const char *target_path;   /* path on target machine */
    size_t     offset;         /* file offset for uprobe */
    bool       retprobe;       /* true = uretprobe (return probe) */
};


static const struct hook_cfg hook_configs[] = {
    {"rm_send_entry", "libvsomeip3.so.3.7.4", "/usr/lib/libvsomeip3.so.3", (size_t)0x0000000000169340, 0},
    {"rm_send_ret", "libvsomeip3.so.3.7.4", "/usr/lib/libvsomeip3.so.3", (size_t)0x0000000000169340, 1},
    {"rm_send_to_entry", "libvsomeip3.so.3.7.4", "/usr/lib/libvsomeip3.so.3", (size_t)0x000000000016a720, 0},
    {"rm_send_to_ret", "libvsomeip3.so.3.7.4", "/usr/lib/libvsomeip3.so.3", (size_t)0x000000000016a720, 1},
    {"rm_on_message", "libvsomeip3.so.3.7.4", "/usr/lib/libvsomeip3.so.3", (size_t)0x0000000000172630, 0},
    {"app_send_entry", "libvsomeip3.so.3.7.4", "/usr/lib/libvsomeip3.so.3", (size_t)0x00000000001bb340, 0},
    {"app_send_ret", "libvsomeip3.so.3.7.4", "/usr/lib/libvsomeip3.so.3", (size_t)0x00000000001bb340, 1},
    {"app_on_message", "libvsomeip3.so.3.7.4", "/usr/lib/libvsomeip3.so.3", (size_t)0x00000000001bc670, 0},
    {"sd_send", "libvsomeip3-sd.so.3.7.4", "/usr/lib/libvsomeip3-sd.so.3", (size_t)0x000000000002c7e0, 0},
    {"sd_process_offer", "libvsomeip3-sd.so.3.7.4", "/usr/lib/libvsomeip3-sd.so.3", (size_t)0x0000000000038a30, 0},
    {"sd_send_subscription", "libvsomeip3-sd.so.3.7.4", "/usr/lib/libvsomeip3-sd.so.3", (size_t)0x0000000000035e80, 0},
    {"sd_handle_subscription", "libvsomeip3-sd.so.3.7.4", "/usr/lib/libvsomeip3-sd.so.3", (size_t)0x000000000002ea30, 0},
};
#define NUM_HOOKS 12

// Generated: 12 hooks resolved, 0 not found
