// Auto-generated by gen_hook_config.sh from config/hooks.json
// DO NOT EDIT MANUALLY
//
// 每个 file 条目 = 一个 Collector 实例
// 新增模块不需改 collector.cpp — 只需加 handler + hooks.json

#pragma once

#include <stddef.h>
#include <stdbool.h>

class StatsCollector;
class ILogWriter;

// 事件处理函数指针（数据驱动，collector.cpp 只调指针不 switch）
typedef void (*event_handler_fn)(const void *data, const char *hook,
                                  StatsCollector *stats, ILogWriter *writer);

struct hook_cfg {
    const char *name;
    const char *target_path;
    size_t     offset;
    bool       retprobe;
};

struct file_group {
    const char *name;
    const void *embed_data;
    unsigned int embed_size;
    const char *ringbuf_map;
    int         module_id;
    int         hook_count;
    const struct hook_cfg *hooks;
    const char **hook_names;
    event_handler_fn handler;    // ★ 扩展点：新增模块只改这行
};


// ── 每个模块的事件处理函数（外部定义，各自一个 .cpp）──────────
extern "C" void routing_event_handler(const void *data, const char *hook, StatsCollector *stats, ILogWriter *writer);
extern "C" void app_event_handler(const void *data, const char *hook, StatsCollector *stats, ILogWriter *writer);
extern "C" void sd_event_handler(const void *data, const char *hook, StatsCollector *stats, ILogWriter *writer);

extern unsigned char routing_bpf_o[];
extern unsigned int  routing_bpf_o_len;
extern unsigned char app_bpf_o[];
extern unsigned int  app_bpf_o_len;
extern unsigned char sd_bpf_o[];
extern unsigned int  sd_bpf_o_len;

// routing
static const struct hook_cfg hook_cfgs_routing[] = {
    {"rm_send_entry","/usr/lib/libvsomeip3.so.3",(size_t)0x0000000000169340,0},
    {"rm_send_ret","/usr/lib/libvsomeip3.so.3",(size_t)0x0000000000169340,1},
    {"rm_send_to_entry","/usr/lib/libvsomeip3.so.3",(size_t)0x000000000016a720,0},
    {"rm_send_to_ret","/usr/lib/libvsomeip3.so.3",(size_t)0x000000000016a720,1},
    {"rm_on_message","/usr/lib/libvsomeip3.so.3",(size_t)0x0000000000172630,0},
};
static const char* hook_names_routing[] = {
    "rm_send_entry",
    "rm_send_ret",
    "rm_send_to_entry",
    "rm_send_to_ret",
    "rm_on_message",
};

// app
static const struct hook_cfg hook_cfgs_app[] = {
    {"app_send_entry","/usr/lib/libvsomeip3.so.3",(size_t)0x00000000001bb340,0},
    {"app_send_ret","/usr/lib/libvsomeip3.so.3",(size_t)0x00000000001bb340,1},
    {"app_on_message","/usr/lib/libvsomeip3.so.3",(size_t)0x00000000001bc670,0},
};
static const char* hook_names_app[] = {
    "app_send_entry",
    "app_send_ret",
    "app_on_message",
};

// sd
static const struct hook_cfg hook_cfgs_sd[] = {
    {"sd_send","/usr/lib/libvsomeip3-sd.so.3",(size_t)0x000000000002c7e0,0},
    {"sd_process_offer","/usr/lib/libvsomeip3-sd.so.3",(size_t)0x0000000000038a30,0},
    {"sd_send_subscription","/usr/lib/libvsomeip3-sd.so.3",(size_t)0x0000000000035e80,0},
    {"sd_handle_subscription","/usr/lib/libvsomeip3-sd.so.3",(size_t)0x000000000002ea30,0},
};
static const char* hook_names_sd[] = {
    "sd_send",
    "sd_process_offer",
    "sd_send_subscription",
    "sd_handle_subscription",
};

static const struct file_group file_groups[] = {
    {"routing",routing_bpf_o,routing_bpf_o_len,"routing_events",1,5,hook_cfgs_routing,hook_names_routing,routing_event_handler},
    {"app",app_bpf_o,app_bpf_o_len,"app_events",2,3,hook_cfgs_app,hook_names_app,app_event_handler},
    {"sd",sd_bpf_o,sd_bpf_o_len,"sd_events",3,4,hook_cfgs_sd,hook_names_sd,sd_event_handler},
};
#define NUM_FILE_GROUPS 3
#define TOTAL_HOOKS 12
// Generated: 12 hooks, 3 file groups
