// Auto-generated by gen_hook_config.sh from config/hooks.json
// DO NOT EDIT — hook_id 编号按 hooks.json 的 hooks[] 顺序生成

#pragma once


// routing
#define HOOK_RM_SEND_ENTRY  0
#define HOOK_RM_SEND_RET  1
#define HOOK_RM_SEND_TO_ENTRY  2
#define HOOK_RM_SEND_TO_RET  3
#define HOOK_RM_ON_MESSAGE  4

// app
#define HOOK_APP_SEND_ENTRY  0
#define HOOK_APP_SEND_RET  1
#define HOOK_APP_ON_MESSAGE  2

// sd
#define HOOK_SD_SEND  0
#define HOOK_SD_PROCESS_OFFER  1
#define HOOK_SD_SEND_SUBSCRIPTION  2
#define HOOK_SD_HANDLE_SUBSCRIPTION  3
